### ISSUE TITLE
Database model

### ISSUE THREAD

**Issue by Arrowana** [ThibautJ/simplyk-platform#22]
We need to clearly define what is the database model, the way we define relation between tables.
Moreover as each platform will access the same database we need to share the models.

For now we have:
Opp
User
Admin
Squad

I am not exactly sure of how it should be done but we have to follow the guidelines of https://docs.mongodb.com/manual/data-modeling/
We can use a google doc to share the design

As discussed with Thibaut, stormpath will be used for registration only and the user ID will be used to link it with our own DB. By creating stormpath_id in User model.

**Comment by ThibautJ** [comment]
Commit : 6c13f5aac90056d31ed6c47bb8c3161fd1c6eadb
