### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by NiclaNN2** [ThibautJ/simplyk-platform#24]
We need to modify the schema of the objects when they are added to the database, so that they comply with data_models_description.json.

e.g : the birth of date of a new user should be a "birthdate" key instead of "birth", according to data_models_description.json.

**Comment by Arrowana** [comment]
I think we should move this file and make each document model as a mangoose object.
The file should be models/models.js, so we can easily import it from any file. In future this folder should be shared between all platform, with a submodule or any automated way.

**Comment by Arrowana** [comment]
Solved by @ThibautJ  by creating the folder models containing each model. The data model will move fast so if we have only one reference, the model itself, it is enough
