### ISSUE TITLE
When one put "favoris" twice on an opportunity on the map, it should stay in "favoris"

### ISSUE THREAD

**Issue by francis31415** [ThibautJ/simplyk-platform#29]
For now an opportunity can be taken out of the favoris list form the map page

**Comment by NiclaNN2** [comment]
yes is it a problem though ?

**Comment by ThibautJ** [comment]
Anyway, take a look to the favToRegis branch and you'll see that this problem is outdated. Now, no more star, a button 'S'inscrire' replace it...
